#!/bin/bash

# Put this in /etc/udev/rules.d/automount.rules
#
# ACTION=="add", ENV{DEVTYPE}=="partition", RUN+="domount %N"

# All based on:
# https://wiki.archlinux.org/index.php/USB_Storage_Devices

# But:
# * run in Ubuntu Quantal on CuBox
# * this file is in /lin/udev ,  not /usr/lib/udev
# * $RANDOM is a bashism, not necessarily in /bin/sh, hence the shebang
# * temp script in /tmp bcause /run is mounted with noexec

#edit the following variables to suit your needs
MYUID=1000              # your user uid
MYGID=1000              # your user gid
MYLOGIN=cubox           # your login
TERM=lxterminal	        # your terminal emulator
MYSHELL=bash            # your shell
export DISPLAY=:0       # your X display

TMPFILE=/tmp/automount.$RANDOM
DIR=`cat /etc/fstab | grep -v '#' | grep $* | awk '{print $2;}'`
if [ "x$DIR" = "x" ]; then
        MYUUID=`blkid -o value -s UUID $*`
        if [ "x$MYUUID" = "x" ]; then
                MYUUID="unknown"
        fi
        DIR=/media/$MYUUID
fi
#mkdir -p /run/media
mkdir -p $DIR
cat > $TMPFILE << EOF
#!/bin/sh
echo "$* will be mounted on $DIR. "
echo "Ctrl-D or exit to unmount."
echo "But exit from the directory first!"
sudo /bin/mount -o uid=$MYUID,gid=$MYGID,user $* $DIR
#cd $DIR
cd
$MYSHELL
cd
sudo /bin/umount -f $DIR && rmdir $DIR
EOF
chmod a+x $TMPFILE
su $MYLOGIN -c "$TERM -t 'Terminal - $* mounted on $DIR' -e $TMPFILE"
sleep 1
#/bin/umount $DIR
rm -f $TMPFILE

